#!/usr/bin/env node
/**
 * codesight-astro — augments .codesight/CODESIGHT.md with the Astro structure
 * codesight (1.14) doesn't parse .astro files, so verdant's map misses every
 * page/route, layout, and the frontmatter imports. This appends them.
 *
 * Idempotent: strips any prior augment block (sentinel-marked) before appending.
 * Run AFTER `codesight`. Wired into post-commit and runnable by hand.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const MAP = join(ROOT, ".codesight", "CODESIGHT.md");
const PAGES = join(ROOT, "src", "pages");
const LAYOUTS = join(ROOT, "src", "layouts");
const START = "<!-- codesight-astro:start -->";
const END = "<!-- codesight-astro:end -->";

if (!existsSync(MAP)) { console.error("no CODESIGHT.md — run codesight first"); process.exit(0); }
if (!existsSync(PAGES)) process.exit(0);

const walk = (dir) => readdirSync(dir).flatMap((n) => {
  const p = join(dir, n);
  return statSync(p).isDirectory() ? walk(p) : [p];
});

const toRoute = (file) => {
  let r = "/" + relative(PAGES, file).replace(/\.astro$/, "").replace(/\\/g, "/");
  r = r.replace(/\/index$/, "") || "/";
  r = r.replace(/\[(\.\.\.)?([^\]]+)\]/g, (_, spread, name) => (spread ? `*${name}` : `:${name}`));
  return r === "" ? "/" : r;
};

const importsOf = (file) => {
  const src = readFileSync(file, "utf-8");
  const fm = src.startsWith("---") ? src.slice(3, src.indexOf("---", 3)) : "";
  const named = [...fm.matchAll(/import\s+([^;]+?)\s+from\s+["']([^"']+)["']/g)]
    .map((m) => m[1].replace(/[{}]/g, "").trim().split(/\s*,\s*/).filter(Boolean).join(", "))
    .filter((s) => s && !s.startsWith("type "));
  const redirect = /Astro\.redirect\(["']([^"']+)["']/.exec(src);
  return { named, redirect: redirect ? redirect[1] : null };
};

const astroPages = walk(PAGES).filter((f) => f.endsWith(".astro")).sort();
const layouts = existsSync(LAYOUTS) ? walk(LAYOUTS).filter((f) => f.endsWith(".astro")).sort() : [];

const lines = [START, "", "# Astro Pages (file-based routes)", ""];
for (const f of astroPages) {
  const rel = relative(ROOT, f);
  const { named, redirect } = importsOf(f);
  const route = toRoute(f);
  let note = redirect ? ` → redirects to \`${redirect}\`` : "";
  const uses = named.length ? ` — uses: ${named.join(", ")}` : "";
  lines.push(`- \`${route}\` — \`${rel}\`${note}${uses}`);
}
if (layouts.length) {
  lines.push("", "# Layouts", "");
  for (const f of layouts) lines.push(`- \`${relative(ROOT, f)}\``);
}
lines.push("", `_Astro section generated by scripts/codesight-astro.mjs (codesight can't parse .astro)_`, END, "");

let md = readFileSync(MAP, "utf-8");
const s = md.indexOf(START), e = md.indexOf(END);
if (s !== -1 && e !== -1) md = md.slice(0, s).replace(/\n+$/, "\n") + md.slice(e + END.length);
md = md.replace(/\n*$/, "\n\n") + lines.join("\n");
writeFileSync(MAP, md);
console.log(`codesight-astro: added ${astroPages.length} pages, ${layouts.length} layouts`);
